name: keepalive

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Streamlit health endpoint
        run: |
          URL="https://aylus-chatbot-eq9gxr7znvagfcki3w9cgh.streamlit.app/_stcore/health"

          # Don't fail the step on curl issues (GitHub runs bash with -e)
          STATUS=$(curl -sS -o /dev/null -m 20 -w "%{http_code}" "$URL" || echo "000")
          echo "HTTP $STATUS"

          # Fetch a tiny body so logs show 'ok'
          curl -sS -m 20 "$URL" | head -c 200 || true
